---
- hosts: "{{ target }}"
  tasks:
  - name: install or upgrade packages
    yum:
      state: latest
      name: "{{ item }}"
    with_items: 
      - bash
      - tcsh
      - zsh
    become: true
    become_user: root
    #when: ansible_distribution == 'CentOS'
    when: ansible_distribution == 'CentOS'
