---
- hosts: "{{ target }}"
  tasks:
  - name: reboot server
    command: /sbin/shutdown -r +1
    become:      true
    become_user: root
  - name: wait for shutdown process
    local_action: pause minutes=2
  - name: check the server to start up
    local_action: wait_for port=22 hosts="{{ inventory_hostname }}" delay=10 timeout=600
