---
- hosts: "{{ target }}"
  vars:
    username: hoge
  vars_prompt:
  - name: "password"
    prompt: "Enter a new user's password"
    private: yes
    encrypt: "md5_crypt"
    confirm: yes
    salt_size: 7
  tasks:
  - name: add a new user on target host
    user:
      name: "{{ username }}"
      password: "{{ password }}"
      group: wheel
    become: true
    become_user: root
  - name: add a new user
    user: name="{{ username }}" state=present
    become: true
    become_user: root
  - name: mkdir .ssh
    file: dest=/home/{{ username }}/.ssh/ state=directory owner={{ username }} mode=700
    become: true
    become_user: root
  - name: setup authorized_keys
    authorized_key: user="{{ username }}"
                    key="{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
    become: true
    become_user: "{{ username }}"

    
